services:
  redis:
    image: redis:6.2.7
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass ORQXAYLE
    volumes:
      - ./redis_data:/data
volumes:
  redis_data:
    driver: local